apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "eos-node.fullname" . }}
  labels:
    app: {{ template "eos-node.name" . }}
    chart: {{ template "eos-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "eos-node.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "eos-node.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: "init-volume"
        image: "{{ .Values.initimage.repository }}:{{ .Values.initimage.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:  ["bash", "/data/setup-state.sh"]
        volumeMounts:
        - name: data
          mountPath: /opt/eosio/bin/data-dir
          {{- if .Values.persistence.subPath }}
          subPath: {{ .Values.persistence.subPath }}
          {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}   
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["nodeos", "--data-dir", "/opt/eosio/bin/data-dir", "--config-dir", "/opt/eosio/bin/data-dir" ]
          ports:
            - name: port-8888
              containerPort: 8888
              protocol: TCP
            - name: port-9876
              containerPort: 9876
              protocol: TCP
#          livenessProbe:
#            exec:
#              command:
#              - test
#              - '`ps -ef | grep eos`'
#          readinessProbe:
#            httpGet:
#              path: /v1/chain/get_info 
#              port: 8888
#              scheme: HTTP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "eos-node.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
